name: Pre-scan CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Weekly security scan

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install bandit safety pipenv

      # Static Application Security Testing (SAST)
      - name: Run Bandit
        run: |
          bandit -r jiragen/ -f json -o bandit-results.json
        continue-on-error: true

      # Software Composition Analysis (SCA)
      - name: Run Safety Scan
        run: |
          safety scan
        continue-on-error: true

      # Secret Scanning
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@latest
        with:
          path: ./
          base: ${{ github.base_ref }}
          head: ${{ github.head_ref }}
          extra_args: --debug --only-verified
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.16/x64
          PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.16/x64/lib/pkgconfig
          Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.16/x64
          Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.16/x64
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.16/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.16/x64/lib

      # Container Scanning
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      # Upload security results
      - name: Upload security results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
          category: Trivy

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests with coverage
        run: |
          tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
